# Generated by Django 6.1 on 2026-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SEDAN', 'Economy Sedan (4 Seats)'), ('SUV', 'Executive SUV (6 Seats)'), ('PREMIUM', 'Luxury Executive (4 Seats)'), ('CHAUFFEUR', 'Driver Rental Only (Customer Car)')], max_length=20, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=8)),
                ('per_minute_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=8)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=120.0, max_digits=8)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('night_charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
