# Generated by Django 6.1 on 2026-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
