# Generated by Django 6.1 on 2026-09-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SEDAN', 'Economy Sedan (4 Seats)'), ('SUV', 'Executive SUV (6 Seats)'), ('PREMIUM', 'Luxury Executive (4 Seats)'), ('CHAUFFEUR', 'Driver Rental Only (Customer Car)')], default='SEDAN', max_length=20)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(default=2022)),
                ('color', models.CharField(default='White', max_length=30)),
                ('seating_capacity', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RC', 'Registration Certificate'), ('INSURANCE', 'Vehicle Insurance'), ('PERMIT', 'Commercial Driving Permit'), ('FITNESS', 'Fitness Certificate')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
        ),
    ]
