# Generated by Django 6.1 on 2026-09-22 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(editable=False, max_length=16, unique=True)),
                ('booking_type', models.CharField(choices=[('TAXI', 'Taxi / Full Vehicle Booking'), ('DRIVER_ONLY', 'Professional Driver Rental (Customer Vehicle)')], default='TAXI', max_length=20)),
                ('vehicle_category', models.CharField(choices=[('SEDAN', 'Economy Sedan (4 Seats)'), ('SUV', 'Executive SUV (6 Seats)'), ('PREMIUM', 'Luxury Executive (4 Seats)'), ('CHAUFFEUR', 'Driver Rental Only (Customer Car)')], default='SEDAN', max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('estimated_distance', models.FloatField(help_text='Distance in KM')),
                ('estimated_duration', models.IntegerField(help_text='Duration in Minutes')),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SEARCHING_DRIVER', 'Searching Nearby Drivers'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('DRIVER_ACCEPTED', 'Driver Accepted'), ('DRIVER_ARRIVING', 'Driver En Route to Pickup'), ('DRIVER_ARRIVED', 'Driver Arrived at Pickup'), ('TRIP_STARTED', 'Trip Started'), ('TRIP_IN_PROGRESS', 'Trip in Progress'), ('TRIP_COMPLETED', 'Trip Completed'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('RATED', 'Rated & Closed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('CANCELLED_BY_DRIVER', 'Cancelled by Driver'), ('CANCELLED_BY_ADMIN', 'Cancelled by Admin'), ('DRIVER_TIMEOUT', 'Driver Request Timeout'), ('NO_DRIVER_AVAILABLE', 'No Drivers Available'), ('PAYMENT_FAILED', 'Payment Failed')], default='REQUESTED', max_length=30)),
                ('payment_status', models.CharField(default='UNPAID', max_length=20)),
                ('payment_method', models.CharField(default='CASH', max_length=30)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Null for immediate bookings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='drivers.driverprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='vehicles.vehicle')),
            ],
        ),
    ]
