# Generated by Django 5.1.15 on 2026-09-23 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats_booked',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_address', models.TextField()),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('departure_datetime', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField(default=3)),
                ('available_seats', models.PositiveIntegerField(default=3)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('vehicle_model', models.CharField(default='Honda City', max_length=100)),
                ('vehicle_number', models.CharField(default='DL-01-AB-1234', max_length=30)),
                ('vehicle_category', models.CharField(choices=[('SEDAN', 'Economy Sedan (4 Seats)'), ('SUV', 'Executive SUV (6 Seats)'), ('PREMIUM', 'Luxury Executive (4 Seats)'), ('CHAUFFEUR', 'Driver Rental Only (Customer Car)')], default='SEDAN', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Passengers'), ('IN_PROGRESS', 'Trip in Progress'), ('COMPLETED', 'Trip Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='ride_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_bookings', to='bookings.rideoffer'),
        ),
    ]
