# Generated by Django 6.1 on 2026-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_seats_booked_rideoffer_booking_ride_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('TAXI', 'Taxi / Full Vehicle Booking'), ('DRIVER_ONLY', 'Professional Driver Rental (Customer Vehicle)'), ('CARPOOL', 'Carpool / Shared Ride')], default='TAXI', max_length=20),
        ),
    ]
